on:
  push: { }
name: Build
jobs:
  client:
    name: Build Client
    strategy:
      matrix:
        PLATFORM:
          - runs-on: ubuntu-latest
          - runs-on: macos-latest
          - runs-on: windows-latest
    runs-on: ${{ matrix.PLATFORM.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
